name: automerge
on:
  workflow_dispatch:
  schedule:
    - cron: '17 2,5,8,11 * * *'

jobs:
  automerge:
    uses: axe312ger/github-workflows/.github/workflows/automerge.yml@main
    secrets: inherit
